### PR TITLE
Bugfix - Context Menu 

### PR DESCRIPTION
**Pull request by stevesobol**
Arnaud,

I wanted to remove the context menu from my Undecorated JavaFX apps but I found a couple issues with doing that. The problem was that the existing code does not check whether the context menu is null or not, before trying to manipulate it. 

My first commit (to my fork) fixed that problem. My other commit fixes a problem I found when I removed the context menu, but left the fullscreen button intact; when you toggle fullscreen mode, the "Fullscreen" context menu is modified - either checked, or unchecked - and obviously, this isn't going to work if there is no context menu. The fix for _this_ problem is simply to make sure fullScreenMenuItem isn't null.

I also fixed an unrelated issue with gitignore (fixed a typo, so now will the dist/ directory will be omitted from future commits).

Thanks, Steve

### CODE REVIEW

**Comment by in-sideFX** [comment]
Hi,
Why did you remove the /bin commit? I may understand but if I merge it will break all links to jars in my blogs.
Thanks

**Comment by stevesobol** [comment]
?? Not sure what you're talking about. There was a typo in .gitignore that was causing the dist/ directory to not be excluded from the commit. I fixed that. If dist/ was supposed to be included in the commit, there shouldn't have been any entry for it in .gitignore in the first place. Am I misunderstanding what's supposed to happen?

If I need to create another commit that doesn't include the change to .gitignore, no problem.

**Comment by in-sideFX** [comment]
Hi, you're right, this was a regression from the previous PR.
/bin was supposed to be pushed. If you can avoid to ignore it, thanks in advance.

**Comment by stevesobol** [comment]
Ahhh. 

Here's what I can do. I can put .gitignore back into the state it was in when I forked your repository, and I can do another commit. That should resolve the problem.

Before I do that: Do you see any issues with my changes? I tested them and they work, but I always appreciate a second (or third, or fourth) opinion. :) Thanks

**Comment by stevesobol** [comment]
Given a choice between trying to fix the commits I've already made, and just starting fresh and including the change to initDecoration(), I think it makes more sense to start fresh and not make a mess, so that's what I'm going to do. I will close this pull request and start over (from step 1 - I'm going to clone the UndecoratorBis repo again).

**Pull request closed without merging**
